services:

  mysawit-plantation:
    build: .
    container_name: mysawit-plantation

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5435/mysawit_plantation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL:-http://host.docker.internal:8080}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key-dev-secret-key-123456}

    ports:
      - "8081:8081"
