services:

  mysawit-postgres:
    image: postgres:16
    container_name: mysawit-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data: